### PR TITLE
Added a variant of Docker-in-Docker with docker compose

### PR DESCRIPTION
**Pull request by LaurentGoderre**
/cc @sylus

### CODE REVIEW

**Comment by tianon** [comment]
Can you explain a bit what the use case for having `docker-compose` inside an image which runs the Docker daemon is?  Normally this'd be accomplished either with `docker-compose` on your host or in a second container (see also [`docker/compose`](https://hub.docker.com/r/docker/compose/)) pointing at the first.

**Comment by LaurentGoderre** [comment]
Certainly and thanks for the quick reply. We need this for our ci that uses dind as the image and we want to test our docker-compose setup

**Comment by tianon** [comment]
Closing this for now in favor of https://github.com/docker/compose/issues/4287 -- we can re-open/reconsider when we hear back from the Compose maintainers on whether this is something they'd like us to pursue.  Thanks! :+1:

**Comment by mbana** [comment]
Hello, any plans to add `docker-compose` to the dind image?

**Pull request closed without merging**
