### PR TITLE
Update to 18.06.0-ce (GA), deprecate Edge releases

### PR DESCRIPTION
**Pull request by tianon**
See https://blog.docker.com/2018/07/extending-support-cycle-docker-community-edition/ and https://docs.docker.com/install/ for more information.

> Docker 18.06 CE will be the last release with a 4-month maintenance lifecycle.
> The planned Docker 18.09 CE release will be supported for 7 months with Docker 19.03 CE being the next release in line.

We do not plan to consume the new nightly builds here because the update frequency will be too high.

FYI @thaJeztah :heart:

### CODE REVIEW

**Comment by tianon** [comment]
```console
$ ./generate-stackbrew-library.sh
# this file is generated via https://github.com/docker-library/docker/blob/595ad0c92090937dcb7c200900fb97e36d36c412/generate-stackbrew-library.sh

Maintainers: Tianon Gravi <tianon@dockerproject.org> (@tianon),
             Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
GitRepo: https://github.com/docker-library/docker.git

Tags: 18.06.0-ce, 18.06.0, 18.06, 18, stable, test, latest
Architectures: amd64, arm32v6, arm64v8, ppc64le, s390x
GitCommit: 595ad0c92090937dcb7c200900fb97e36d36c412
Directory: 18.06

Tags: 18.06.0-ce-dind, 18.06.0-dind, 18.06-dind, 18-dind, stable-dind, test-dind, dind
Architectures: amd64, arm32v6, arm64v8, ppc64le, s390x
GitCommit: 595ad0c92090937dcb7c200900fb97e36d36c412
Directory: 18.06/dind

Tags: 18.06.0-ce-git, 18.06.0-git, 18.06-git, 18-git, stable-git, test-git, git
Architectures: amd64, arm32v6, arm64v8, ppc64le, s390x
GitCommit: 595ad0c92090937dcb7c200900fb97e36d36c412
Directory: 18.06/git

$ ./update.sh
18.06: 18.06.0-ce (stable)
```

**Comment by tianon** [comment]
@thaJeztah I note that 18.06.0 is still pushed to https://download.docker.com/linux/static/edge/ -- should we still tag this release as `docker:edge`?

**Comment by thaJeztah** [comment]
@tianon good catch; we're pushing to "edge", so that people that only subscribed to the "edge" channel wouldn't miss out on getting the stable releases (in other words; make sure that "edge" gets a release each month, and not skip the month that happens to be a stable release).

If we previously tagged those releases as "edge" as well; I'd say: yes, let's do it one more time to close the chapter.

(Hope I make sense  here 😅)

> We do not plan to consume the new nightly builds here because the update frequency will be too high.

understandable; I'll check with the release team as well if they had plans to push automated nightly builds somewhere

**Comment by tianon** [comment]
Perfect sense, thanks :+1:

**Pull request merged**
