### PR TITLE
Add "buildx" and "compose" CLI plugins (for supported architectures of each)

### LINKED ISSUE #303: DinD with docker-compose
After following the guide in https://hub.docker.com/_/docker/ I wrote this docker-compose.yaml that should setup the same as the shell commands (if I understood it correctly):

``` yaml
version: "3.8"

services:
  dind:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    networks:
      - docker
    volumes:
      - docker-certs-ca:/certs
      - docker-certs-client:/certs/client

  docker-client:
    image: docker
    environment:
      DOCKER_TLS_CERTDIR: /certs
    # Just loop at infinitum, we will get to this container by `docker exec`ing
    command: [sh, -c, "while sleep 1; do :; done"]
    networks:
      - docker
    depends_on:
      - dind
    volumes:
      - docker-certs-client:/certs/client:ro

volumes:
  docker-certs-ca:
  docker-certs-client:

networks:
  docker:
```

After running `docker-compose exec docker-client docker version` I got the following error, and I cannot connect to the dind docker from the docker-client:

```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:11 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Is there anything I'm missing in my docker-compose.yml?

Running the commands from the README manually I get the correct result

### LINKED ISSUE #355: Why doesn't `docker:latest` image contains the compose?
When I tried to run `docker compose up` I got `docker: 'compose' is not a docker command.` but in `docker:dind` always good. Maybe `compose` missed from `docker:latest` image?

### PR DESCRIPTION
**Pull request by tianon**
- Closes #303
- Closes #355
- Closes https://github.com/docker/roadmap/issues/322

(I don't actually have permission for this to auto-close https://github.com/docker/roadmap/issues/322, so maybe someone like @thaJeztah or @chris-crone can do the honors once we get this in.)

Refs:
- #18
- #30
- #42
- #156
- #243
- #313
- https://github.com/docker/compose/issues/8871
- https://github.com/docker/roadmap/issues/256
- https://github.com/docker/docker-ce-packaging/pull/309

As a warning, this does very severely bloat the size of the Docker images (something like 100MiB more), but given these are part of the "Docker Experience" I think it makes sense. :see_no_evil:

### CODE REVIEW

**Comment by tao12345666333** [comment]
👍 great!

By the way, can we provide a tag like non-plugin, which means that plugin is not included.

Because in our actual scenario, DinD is heavily used in CI without the need to use plugins.  It would be nice to not increase the size of the image. Thanks

**Comment by tianon** [comment]
:see_no_evil: that's exactly the type of request I've been hoping to avoid all this time :sweat_smile:

If anything, I'd love to maintain _less_ variations of this image than more. :innocent:

I've also been _very_ strongly considering moving from Alpine to Debian or Ubuntu for the next (22.xx) release, since the experience of using Docker-Inc-provided Docker builds on both of those platforms is much more well-supported than Alpine is. :disappointed:

**Comment by johnthagen** [comment]
> I've also been very strongly considering moving from Alpine to Debian or Ubuntu for the next (22.xx) release

As a drive by comment, I too will say that I've hit rough edged working with the Alpine-derived Docker images. If you don't need to do any changes they work well, but the moment you want to add some scripts or anything else to image Alpine is harder to use.

Also big ❤️ for getting Compose v2 into an official image.

**Comment by tianon** [comment]
With the implementation currently in this PR, new versions of Compose will be integrated as they're released (so you'd have to pin to an image digest if you want something that doesn't change).

**Comment by wedi** [comment]
I am used to Alpine from the times when there was no great slim alternative and I have been sticking to it to copy and paste proven recipes. Now that we have, for example, an Ubuntu image with a footprint below 30 MB, I think that in principle it would be fine to switch. However, please keep in mind how many people use these images. Making the switch will easily require thousands of developer hours in downstream projects and Pipelines. So it would be nice if you kept it as long as it doesn't become a major drain on your time.

**Comment by wedi** [comment]
Once merged this would allow to finally resolve https://github.com/docker-library/docker/issues/156.

**Comment by tianon** [comment]
Just to record this somewhere, I did some testing on combining layers here to see if we get some compression efficiencies on transport (h/t @chris-crone), and the answer is a big resounding "no" -- building this as-is, the total "compressed size" of all layers is 89.47MB.  If I combine both plugins layers into a single one, it's the same.  Even if I combine the full Docker/containerd binaries layer as well, it's still exactly the same. :grimacing:

(So my preference is to continue to leave them separate.)

**Comment by tianon** [comment]
I guess this is also a good place to note that the comparison to "current" from that is ~66.99MB, so for transport, this is not a _huge_ increase.

**Comment by chris-crone** [comment]
> Just to record this somewhere, I did some testing on combining layers here to see if we get some compression efficiencies on transport (h/t @chris-crone), and the answer is a big resounding "no" -- building this as-is, the total "compressed size" of all layers is 89.47MB. If I combine both plugins layers into a single one, it's the same. Even if I combine the full Docker/containerd binaries layer as well, it's still exactly the same. 😬
> 
> (So my preference is to continue to leave them separate.)

I was so sure that gzip would make the duplicated Go runtime go away but alas 😢

**Comment by johnthagen** [comment]
Now that Compose v2 is included in the [`docker`](https://hub.docker.com/_/docker) image, should [`docker/compose` (v1)](https://hub.docker.com/r/docker/compose) be updated with a notice that it deprecated?

**Comment by johnthagen** [comment]
@tianon I don't know if it's moving up to Compose v2 or buildx or some combination, but when we moved our CI that runs `docker/compose:1.29.2`/`docker-compose build --parallel` -> `docker`/`docker compose build` our compose project (multiple multi-stage Dockerfiles) built **twice** as fast. ❤️ 

Thanks!

**Pull request merged**
