### PR TITLE
[WIP] add windows dockerfile

### PR DESCRIPTION
**Pull request by friism**
1. The next Windows version has support for bind-mounting the Windows Docker engine named pipe
2. This means it's meaningful to have an image with just `docker.exe` in it
3. In this new version, `nanoserver` doesn't have PowerShell anymore, so you're fully reliant on a builder image to get set up: https://docs.microsoft.com/en-us/windows-server/get-started/nano-in-semi-annual-channel

This PR can be tested with:

1. requires late-model windows insider (I tested on 16278)
2. ` Get-Content .\17.09-rc\windows\Dockerfile | docker build -t docker -`
3. 

```
docker run  -v \\.\pipe\docker_engine:\\.\pipe\docker_engine docker version
Client:
 Version:      17.09.0-ce-rc1
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   ae21824
 Built:        Wed Sep  6 22:25:14 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce-rc1
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   ae21824
 Built:        Wed Sep  6 22:35:40 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

### CODE REVIEW

**Comment by tianon** [comment]
This move to "powerless" Nano Server is going to be a very, very irritating compatibility break across the board. :disappointed: (PowerShell makes Nano Server actually useful IMO -- without PowerShell, it might as well just be "`FROM scratch` for Windows" instead of "Alpine for Windows", which is essentially what it is today -- both have a place, but I'd argue that Alpine is way more useful and usable for almost all use cases.)

On that note, being able to support multi-stage builds is something we'd like official images to be able to do, but there is a _lot_ of work we have to do before we can really get there (see https://github.com/docker-library/official-images/issues/3383 for more details on that, especially https://github.com/docker-library/official-images/issues/3383#issuecomment-329259161 which is a non-exhaustive list of things that need to happen besides "just" updating all our nodes to Docker 17.05+).

I'd be 100% +1 on `windowsservercore`-based image variants in the meantime, though!

**Comment by friism** [comment]
updated

**Comment by tianon** [comment]
Sorry for the hyper-long delay. :disappointed:

I've rebased this, and updated it to include both the necessary changes to `generate-stackbrew-library.sh` and `update.sh`, use a template file, and added it for all currently-supported versions. :+1: :heart:

(I'll probably add AppVeyor to verify the builds in a separate PR later. :+1:)

**Comment by tianon** [comment]
A few useful outputs:
```console
$ ./update.sh
17.06: 17.06.2-ce (stable)
17.07: 17.07.0-ce (edge)
17.09: 17.09.0-ce (stable)
17.10-rc: 17.10.0-ce-rc2 (test)
```
```diff
$ diff -u <(bashbrew cat docker) <(bashbrew cat <(./generate-stackbrew-library.sh))
--- /dev/fd/63	2017-10-12 16:52:37.998420528 -0700
+++ /dev/fd/62	2017-10-12 16:52:37.998420528 -0700
@@ -13,6 +13,12 @@
 GitCommit: 8ada62f762b30d09fd54664710c0ef3b64038f07
 Directory: 17.10-rc/git
 
+Tags: 17.10.0-ce-rc2-windowsservercore, 17.10-rc-windowsservercore, rc-windowsservercore
+Architectures: windows-amd64
+GitCommit: 2f6926c4fb37274b90fae3ba6c3320619a8d0289
+Directory: 17.10-rc/windows/windowsservercore
+Constraints: windowsservercore
+
 Tags: 17.09.0-ce, 17.09.0, 17.09, 17, stable, test, edge, latest
 GitCommit: 454a0ff9e99d4fde7112b25d64d25f940ab28a99
 Directory: 17.09
@@ -25,6 +31,12 @@
 GitCommit: a6b52c73daa8283cd861f41f55e53426008708ac
 Directory: 17.09/git
 
+Tags: 17.09.0-ce-windowsservercore, 17.09.0-windowsservercore, 17.09-windowsservercore, 17-windowsservercore, stable-windowsservercore, test-windowsservercore, edge-windowsservercore, windowsservercore
+Architectures: windows-amd64
+GitCommit: 2f6926c4fb37274b90fae3ba6c3320619a8d0289
+Directory: 17.09/windows/windowsservercore
+Constraints: windowsservercore
+
 Tags: 17.07.0-ce, 17.07.0, 17.07
 GitCommit: 454a0ff9e99d4fde7112b25d64d25f940ab28a99
 Directory: 17.07
@@ -37,6 +49,12 @@
 GitCommit: a8f8fa1b57349cc22c80e7d6cbbdb512ffee2bd2
 Directory: 17.07/git
 
+Tags: 17.07.0-ce-windowsservercore, 17.07.0-windowsservercore, 17.07-windowsservercore
+Architectures: windows-amd64
+GitCommit: 2f6926c4fb37274b90fae3ba6c3320619a8d0289
+Directory: 17.07/windows/windowsservercore
+Constraints: windowsservercore
+
 Tags: 17.06.2-ce, 17.06.2, 17.06
 GitCommit: 454a0ff9e99d4fde7112b25d64d25f940ab28a99
 Directory: 17.06
@@ -48,3 +66,9 @@
 Tags: 17.06.2-ce-git, 17.06.2-git, 17.06-git
 GitCommit: 168a6d227d021c6d38c3986b7c668702ec172fa7
 Directory: 17.06/git
+
+Tags: 17.06.2-ce-windowsservercore, 17.06.2-windowsservercore, 17.06-windowsservercore
+Architectures: windows-amd64
+GitCommit: 2f6926c4fb37274b90fae3ba6c3320619a8d0289
+Directory: 17.06/windows/windowsservercore
+Constraints: windowsservercore
```

**Comment by tianon** [comment]
I have also personally built and verified all four versions, and they all build successfully and have the appropriate output during the `Verifying` stage of the `Dockerfile`. :+1:

**Comment by tianon** [comment]
... and now AppVeyor is enabled and Green for this repo: https://github.com/docker-library/docker/pull/85 :+1: :metal:

**Pull request merged**
