### PR TITLE
Add 17.03-rc

### PR DESCRIPTION
**Pull request by yosifkit**

### CODE REVIEW

**Comment by tianon** [comment]
We need to update the generate script too right?

**Comment by yosifkit** [comment]
Ah, the `17` tag.
```console
$ ./generate-stackbrew-library.sh
# this file is generated via https://github.com/docker-library/docker/blob/b202ec7e529f5426e2ad7e8c0a8b82cacd406573/generate-stackbrew-library.sh

Maintainers: Tianon Gravi <tianon@dockerproject.org> (@tianon),
             Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
GitRepo: https://github.com/docker-library/docker.git

Tags: 17.03.0-ce-rc1, 17.03-rc
GitCommit: 06717e6f2add8226068bec54abb23e646dea90e0
Directory: 17.03-rc

Tags: 17.03.0-ce-rc1-dind, 17.03-rc-dind
GitCommit: 06717e6f2add8226068bec54abb23e646dea90e0
Directory: 17.03-rc/dind

Tags: 17.03.0-ce-rc1-git, 17.03-rc-git
GitCommit: 06717e6f2add8226068bec54abb23e646dea90e0
Directory: 17.03-rc/git

Tags: 1.13.1, 1.13, 1, latest
GitCommit: 50ec917e1b7601d655daee8893567e8cfd213248
Directory: 1.13

Tags: 1.13.1-dind, 1.13-dind, 1-dind, dind
GitCommit: b202ec7e529f5426e2ad7e8c0a8b82cacd406573
Directory: 1.13/dind

Tags: 1.13.1-git, 1.13-git, 1-git, git
GitCommit: b202ec7e529f5426e2ad7e8c0a8b82cacd406573
Directory: 1.13/git

Tags: 1.12.6, 1.12
GitCommit: 05678f7f3198d0787d78de9bdc084dcffccf7276
Directory: 1.12

Tags: 1.12.6-dind, 1.12-dind
GitCommit: c1af76ec4c97ff24dcf6675b55b12105216dc711
Directory: 1.12/dind

Tags: 1.12.6-git, 1.12-git
GitCommit: 746d9052066ccfbcb98df7d9ae71cf05d8877419
Directory: 1.12/git

Tags: 1.12.6-experimental, 1.12-experimental
GitCommit: 05678f7f3198d0787d78de9bdc084dcffccf7276
Directory: 1.12/experimental

Tags: 1.12.6-experimental-dind, 1.12-experimental-dind
GitCommit: c1af76ec4c97ff24dcf6675b55b12105216dc711
Directory: 1.12/experimental/dind

Tags: 1.12.6-experimental-git, 1.12-experimental-git
GitCommit: eb714a73e7e3f87705f468c3c6e9f4e316136bf5
Directory: 1.12/experimental/git
```

**Comment by yosifkit** [comment]
❓  `Tags: 17.03.0-ce-rc1, 17.03-rc, 17, rc`

**Comment by yosifkit** [comment]
```console
$ ./generate-stackbrew-library.sh
# this file is generated via https://github.com/docker-library/docker/blob/21c954a70560f765490efc2f60e12e971fcafc77/generate-stackbrew-library.sh

Maintainers: Tianon Gravi <tianon@dockerproject.org> (@tianon),
             Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
GitRepo: https://github.com/docker-library/docker.git

Tags: 17.03.0-ce-rc1, 17.03-rc, rc
GitCommit: 06717e6f2add8226068bec54abb23e646dea90e0
Directory: 17.03-rc

Tags: 17.03.0-ce-rc1-dind, 17.03-rc-dind, rc-dind
GitCommit: 06717e6f2add8226068bec54abb23e646dea90e0
Directory: 17.03-rc/dind

Tags: 17.03.0-ce-rc1-git, 17.03-rc-git, rc-git
GitCommit: 06717e6f2add8226068bec54abb23e646dea90e0
Directory: 17.03-rc/git

#### end of important bits
```

**Comment by tianon** [comment]
LGTM

**Comment by yosifkit** [comment]
'Tis greeen 💚

**Pull request merged**
