### PR TITLE
Fix host networking

### PR DESCRIPTION
**Pull request by lukechilds**
Resolves https://github.com/docker-library/docker/issues/443

I think the iptables behaviour is a bug but the `DOCKER_ENSURE_BRIDGE` behaviour might be considered out of scope. It's pretty handy if you're using host networking though and it shouldn't affect anyone that doesn't have it set so it would be great to include it if people think it's appropriate.

### CODE REVIEW

**Review by Luisvelix — COMMENTED** [review]
[Uploading CHANGELOG.txt…]()

**Comment by Luisvelix** [comment]
[README-win32.txt](https://github.com/docker-library/docker/files/12643082/README-win32.txt)

**Comment by tianon** [comment]
See https://github.com/docker-library/docker/pull/437#issuecomment-1845920765

**Comment by tianon** [comment]
Closing in favor of https://github.com/docker-library/docker/pull/437 (`DOCKER_ENSURE_BRIDGE` is definitely out of scope, sorry!)

**Pull request closed without merging**
